---
engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
	checks:
		#disable Namespaces NamespaceDeclaration BlankLineAfter check as it does not work properly
		PSR2 Namespaces NamespaceDeclaration BlankLineAfter:
			enabled: false
  phpmd:
    enabled: true  
    checks:
      #disable else expression checks, #savetheelse
      CleanCode/ElseExpression:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - php


ratings:
  paths: ["Famoser.SyncApi.Webpage/src/**/*"]
exclude_paths: ["Famoser.SyncApi.Webpage/src/public/assets/**/*"]
