language: php

php:
    - 7.0
    - 7.1
    - nightly
    
install:
    - cd Famoser.SyncApi.Webpage
    - composer install --dev

after_script:
  - ./vendor/bin/test-reporter
  - php ./vendor/bin/codacycoverage clover ./build/logs/clover.xml
